export enum AgreementStatus {
  ACTIVE = 'ACTIVE',
  EXPIRED = 'EXPIRED',
  TERMINATED = 'TERMINATED',
  PENDING = 'PENDING',
  INACTIVE = 'INACTIVE',
  RENEWED = 'RENEWED',
  AMENDED = 'AMENDED',
  LAPSED = 'LAPSED',
  ACTIVE_PENDING_RENEWAL = 'ACTIVE_PENDING_RENEWAL',
  VOID = 'VOID'
}
