export enum ManagerStatus {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  SUSPENDED = 'SUSPENDED',
  TERMINATED = 'TERMINATED',
  ON_LEAVE = 'ON_LEAVE',
  PROBATIONARY = 'PROBATIONARY',
  PROMOTED = 'PROMOTED',
  DEMOTED = 'DEMOTED',
  TRANSFERRED = 'TRANSFERRED',
  RETIRED = 'RETIRED'
}
