export enum ProductStatus {
  ACTIVE = "ACTIVE",
  INACTIVE = "INACTIVE",
  TEMPORARILY_UNAVAILABLE = "TEMPORARILY_UNAVAILABLE",
  PENDING_APPROVAL = "PENDING_APPROVAL",
  ON_HOLD = "ON_HOLD",
  RESTRICTED = "RESTRICTED",
  PILOT = "PILOT"
}
